spring.application.name=gestaoescolar
spring.datasource.url=jdbc:mysql://localhost/gestaoescolar?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.mvc.hiddenmethod.filter.enabled=true
spring.security.exceptionHandling.accessDeniedPage=/error/403